name: (Cloud)Kernel Builder Xiaomi 10 Ultra

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout zipper
      uses: actions/checkout@v2
      with:
        repository: lemniskett/AnyKernel3
        path: zipper
    - name: Integrate KernelSU
      run: |


        sudo apt install tree
        tree .
    - name: Android kernel build
      uses: lemniskett/android-kernel-actions@master
      id: build
      env:
        KERNEL_PATH: source
      with:
        arch: arm64
        compiler: proton-clang/master/binutils
        defconfig: cas_defconfig
        image: Image
    - name: Upload Build
      uses: actions/upload-artifact@v3
      with:
        name: Image
        path: /home/runner/work/kernel-su-huawei-nova2/kernel-su-huawei-nova2/zipper
